[[Ipopt]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6b3b6af703dccc3cfcd581ff383ac10ca48904b3"
libc = "glibc"
os = "linux"

    [[Ipopt.download]]
    sha256 = "a196c9aa2f3cc1751b006c11085c071ec8f8b8f090df03c99f8be331636bdd54"
    url = "https://github.com/JuliaBinaryWrappers/Ipopt_jll.jl/releases/download/Ipopt-v3.13.4+1/Ipopt.v3.13.4.aarch64-linux-gnu-cxx03.tar.gz"
[[Ipopt]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1e682d264713870fd91f98367139695a41bb15e0"
libc = "glibc"
os = "linux"

    [[Ipopt.download]]
    sha256 = "448bb1bc4065ec43bb6697dcefd59314ece4f0ab65e2c0d6b6081bc7be28355e"
    url = "https://github.com/JuliaBinaryWrappers/Ipopt_jll.jl/releases/download/Ipopt-v3.13.4+1/Ipopt.v3.13.4.aarch64-linux-gnu-cxx11.tar.gz"
[[Ipopt]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1301edddd2577d06926c8e58c570028a043edcb6"
libc = "musl"
os = "linux"

    [[Ipopt.download]]
    sha256 = "9270f24d6b44bd0bcd7eff1db6ea28fccd048128433bc10c0dea78453579cec7"
    url = "https://github.com/JuliaBinaryWrappers/Ipopt_jll.jl/releases/download/Ipopt-v3.13.4+1/Ipopt.v3.13.4.aarch64-linux-musl-cxx03.tar.gz"
[[Ipopt]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eee549b1678c8d6ec9202947d733bf00cc0e5900"
libc = "musl"
os = "linux"

    [[Ipopt.download]]
    sha256 = "20c886d1033c4d3552bbe85eba536f604aa070d276e97fe85d0daae551e021c7"
    url = "https://github.com/JuliaBinaryWrappers/Ipopt_jll.jl/releases/download/Ipopt-v3.13.4+1/Ipopt.v3.13.4.aarch64-linux-musl-cxx11.tar.gz"
[[Ipopt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4341b96f7a7ba840c357e5e123c14aa513b68397"
libc = "glibc"
os = "linux"

    [[Ipopt.download]]
    sha256 = "c643324492c277265af1ce299d9af2b4fea0eedfafb1be0436f1af40938f9dbe"
    url = "https://github.com/JuliaBinaryWrappers/Ipopt_jll.jl/releases/download/Ipopt-v3.13.4+1/Ipopt.v3.13.4.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Ipopt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aa96bb4a194286a6f840ca045344de10b54269ea"
libc = "glibc"
os = "linux"

    [[Ipopt.download]]
    sha256 = "a7c5b49f1b6170c3b2c16ace1a0a87a21276b1adfd7955e470b3aba0395cb2b9"
    url = "https://github.com/JuliaBinaryWrappers/Ipopt_jll.jl/releases/download/Ipopt-v3.13.4+1/Ipopt.v3.13.4.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Ipopt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0aa84314309db15bae6de9b76d38d1f529e0032f"
libc = "musl"
os = "linux"

    [[Ipopt.download]]
    sha256 = "caa127e71894aef07d6ef30d6badbfe9551fa1ad20c08d74bea23ceb5fcd3d60"
    url = "https://github.com/JuliaBinaryWrappers/Ipopt_jll.jl/releases/download/Ipopt-v3.13.4+1/Ipopt.v3.13.4.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Ipopt]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1ed8c547941d560c82798eefb0d8408974a335b2"
libc = "musl"
os = "linux"

    [[Ipopt.download]]
    sha256 = "bc4da7b532acc367579cd7935f5643a4529f3f250912b5203038a37dc5f3ce1b"
    url = "https://github.com/JuliaBinaryWrappers/Ipopt_jll.jl/releases/download/Ipopt-v3.13.4+1/Ipopt.v3.13.4.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Ipopt]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a81033e2f081ea4cff6b9f57ccc20193d7bc3097"
libc = "glibc"
os = "linux"

    [[Ipopt.download]]
    sha256 = "c5c2c6bdda057141275f64ff299057e890729996f15ac262642fd646a6028097"
    url = "https://github.com/JuliaBinaryWrappers/Ipopt_jll.jl/releases/download/Ipopt-v3.13.4+1/Ipopt.v3.13.4.i686-linux-gnu-cxx03.tar.gz"
[[Ipopt]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b169f977e5b649058ca81cb5e7a3e13c27160d3"
libc = "glibc"
os = "linux"

    [[Ipopt.download]]
    sha256 = "9542a37392f03736b6110d81724c913731dde9192eeb1af1fb9e6dee9832dc8c"
    url = "https://github.com/JuliaBinaryWrappers/Ipopt_jll.jl/releases/download/Ipopt-v3.13.4+1/Ipopt.v3.13.4.i686-linux-gnu-cxx11.tar.gz"
[[Ipopt]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bf8f150809960a200146c8b2d68761b9ae2b7174"
libc = "musl"
os = "linux"

    [[Ipopt.download]]
    sha256 = "747b782af5e2e07fdd8c3e46c45681ade96faa1914507627b9c57310308d4f11"
    url = "https://github.com/JuliaBinaryWrappers/Ipopt_jll.jl/releases/download/Ipopt-v3.13.4+1/Ipopt.v3.13.4.i686-linux-musl-cxx03.tar.gz"
[[Ipopt]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6905d97b5e7bcfd51963b9763c5817693800cd2d"
libc = "musl"
os = "linux"

    [[Ipopt.download]]
    sha256 = "a124cc037f108f0364495584ee4fae574a492a658ec7576e783ba1267e725d88"
    url = "https://github.com/JuliaBinaryWrappers/Ipopt_jll.jl/releases/download/Ipopt-v3.13.4+1/Ipopt.v3.13.4.i686-linux-musl-cxx11.tar.gz"
[[Ipopt]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "149b35cb81ef293f94aad2e792c7335f41d993da"
os = "windows"

    [[Ipopt.download]]
    sha256 = "5f13ad2df025f107881c608fafb1b679a3c1bd6d8ad24807de5cbbf4d1f9882d"
    url = "https://github.com/JuliaBinaryWrappers/Ipopt_jll.jl/releases/download/Ipopt-v3.13.4+1/Ipopt.v3.13.4.i686-w64-mingw32-cxx03.tar.gz"
[[Ipopt]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dc830beb20c55437f11f5087404b541dce072dbd"
os = "windows"

    [[Ipopt.download]]
    sha256 = "73bd20bab9621e796c566a2a27cd92da78d33d881812bcdf54cffcfd50b5bb18"
    url = "https://github.com/JuliaBinaryWrappers/Ipopt_jll.jl/releases/download/Ipopt-v3.13.4+1/Ipopt.v3.13.4.i686-w64-mingw32-cxx11.tar.gz"
[[Ipopt]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a10392a3eebf106404194f568a231c646a9eebe5"
libc = "glibc"
os = "linux"

    [[Ipopt.download]]
    sha256 = "357b40f9fb0719731c019486bbd233e4d71f3039204f7bce0f6bf30439b23925"
    url = "https://github.com/JuliaBinaryWrappers/Ipopt_jll.jl/releases/download/Ipopt-v3.13.4+1/Ipopt.v3.13.4.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Ipopt]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a59e1d2f4b9cd5c17553ec4aa661b6a43023addc"
libc = "glibc"
os = "linux"

    [[Ipopt.download]]
    sha256 = "792301190319ab7923b49d476ac51829320cdbd299d24ca4ab084acf8f46f040"
    url = "https://github.com/JuliaBinaryWrappers/Ipopt_jll.jl/releases/download/Ipopt-v3.13.4+1/Ipopt.v3.13.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Ipopt]]
arch = "x86_64"
git-tree-sha1 = "8cddcffbcb1fa9a54148f826b47a0c4548c3b2ee"
os = "macos"

    [[Ipopt.download]]
    sha256 = "a34e608075fbf3e26bb06335f7ac494e02813fde3ee82926ce2391fb046338fe"
    url = "https://github.com/JuliaBinaryWrappers/Ipopt_jll.jl/releases/download/Ipopt-v3.13.4+1/Ipopt.v3.13.4.x86_64-apple-darwin.tar.gz"
[[Ipopt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0441c0cd0edd9d79504098e339514f8d54155b4e"
libc = "glibc"
os = "linux"

    [[Ipopt.download]]
    sha256 = "4e57f29b6639a8e55643ec8ce750184af8d197494ef43240725d2afe7b611099"
    url = "https://github.com/JuliaBinaryWrappers/Ipopt_jll.jl/releases/download/Ipopt-v3.13.4+1/Ipopt.v3.13.4.x86_64-linux-gnu-cxx03.tar.gz"
[[Ipopt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e9a9b64c2269b75f7c5a295549858b9c25b820eb"
libc = "glibc"
os = "linux"

    [[Ipopt.download]]
    sha256 = "0a9c587d906f5c3c73496d4cb820fe24fab9b381b54a85eee447d6ac85aec6dc"
    url = "https://github.com/JuliaBinaryWrappers/Ipopt_jll.jl/releases/download/Ipopt-v3.13.4+1/Ipopt.v3.13.4.x86_64-linux-gnu-cxx11.tar.gz"
[[Ipopt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8fefe752cf3529b3d79c10359a19f3b38bfd9081"
libc = "musl"
os = "linux"

    [[Ipopt.download]]
    sha256 = "83343b598010c796c70e34a1c9142e364d23ac60e370e277aeb35ca909436217"
    url = "https://github.com/JuliaBinaryWrappers/Ipopt_jll.jl/releases/download/Ipopt-v3.13.4+1/Ipopt.v3.13.4.x86_64-linux-musl-cxx03.tar.gz"
[[Ipopt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dc520d9a0c67edb98eb98ab51dad78f13b5ef967"
libc = "musl"
os = "linux"

    [[Ipopt.download]]
    sha256 = "02e4e2e68c780c24db450b73c5bdcfb5569634090e7053b92afcbf18ac252567"
    url = "https://github.com/JuliaBinaryWrappers/Ipopt_jll.jl/releases/download/Ipopt-v3.13.4+1/Ipopt.v3.13.4.x86_64-linux-musl-cxx11.tar.gz"
[[Ipopt]]
arch = "x86_64"
git-tree-sha1 = "db98adb58507315dc5faf2555aeb2fe3609cc93e"
os = "freebsd"

    [[Ipopt.download]]
    sha256 = "c760b8afe1dea59f589b38d96e85ebf57725a3e76d185da93bb0b12a4ea2bad7"
    url = "https://github.com/JuliaBinaryWrappers/Ipopt_jll.jl/releases/download/Ipopt-v3.13.4+1/Ipopt.v3.13.4.x86_64-unknown-freebsd.tar.gz"
[[Ipopt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c57a71f7ee8f915441246f3d3ee7903af9c02284"
os = "windows"

    [[Ipopt.download]]
    sha256 = "63f020114701973b210b71411d2106adaf105d7a26e41ef4a8112cd2bbee8e27"
    url = "https://github.com/JuliaBinaryWrappers/Ipopt_jll.jl/releases/download/Ipopt-v3.13.4+1/Ipopt.v3.13.4.x86_64-w64-mingw32-cxx03.tar.gz"
[[Ipopt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4aaab967098581f57d89476cde8b27169bb201b0"
os = "windows"

    [[Ipopt.download]]
    sha256 = "d6322cf9099c2c2ee81798e5f84a89f49e21041f612be411696f6eef3ca35d5a"
    url = "https://github.com/JuliaBinaryWrappers/Ipopt_jll.jl/releases/download/Ipopt-v3.13.4+1/Ipopt.v3.13.4.x86_64-w64-mingw32-cxx11.tar.gz"
