# Autogenerated wrapper script for Ipopt_jll for armv7l-linux-musleabihf-libgfortran5-cxx11
export amplexe, libipopt, libipoptamplinterface

using ASL_jll
using MUMPS_seq_jll
using SPRAL_jll
using libblastrampoline_jll
using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("Ipopt")
JLLWrappers.@declare_library_product(libipopt, "libipopt.so.3")
JLLWrappers.@declare_library_product(libipoptamplinterface, "libipoptamplinterface.so.3")
JLLWrappers.@declare_executable_product(amplexe)
function __init__()
    JLLWrappers.@generate_init_header(ASL_jll, MUMPS_seq_jll, SPRAL_jll, libblastrampoline_jll, CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libipopt,
        "lib/libipopt.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libipoptamplinterface,
        "lib/libipoptamplinterface.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        amplexe,
        "bin/ipopt",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
